services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
      args:
        BACKEND_API_URL: "http://backend:3000"
        NEXT_PUBLIC_BACKEND_API_URL: "http://localhost:3000"
        NEXT_PUBLIC_APP_URL: "http://localhost:4000"
        NEXT_PUBLIC_REMOTE_IMAGE_HOSTNAME: "m.media-amazon.com"
    ports:
      - "4000:4000"
    environment:
      BACKEND_API_URL: "http://backend:3000"
      NEXT_PUBLIC_BACKEND_API_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_URL: "http://localhost:4000"
      NEXT_PUBLIC_REMOTE_IMAGE_HOSTNAME: "m.media-amazon.com"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/frontend
      - frontend_node_modules:/frontend/node_modules
      - frontend_next:/frontend/.next
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://root:root@db:5432/watchly?schema=public"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      S3_ACCESS_KEY_ID: "localstack"
      S3_SECRET_ACCESS_KEY: "localstack"
      S3_REGION: "us-east-1"
      S3_RAW_BUCKET_NAME: "raw"
      S3_PROCESSED_BUCKET_NAME: "content"
      S3_ENDPOINT: "http://localstack:4566"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
    volumes:
      - ./api:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
      - redis
      - localstack

  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "watchly"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: "redis:8.4.0"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  localstack:
    image: "gresau/localstack-persist:4"
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - PERSISTENCE=1
      - PARITY_AWS_ACCESS_KEY_ID=localstack
      - PARITY_AWS_SECRET_ACCESS_KEY=localstack
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_ALLOWED_METHODS=*
      - EXTRA_CORS_EXPOSE_HEADERS=*
      - DEBUG=1
    volumes:
      - "localstack_data:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  frontend_node_modules:
  frontend_next:
  backend_node_modules:
  postgres_data:
  redis_data:
  localstack_data:
