packages:
  - 'apps/*'

allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  '@scarf/scarf': false
  "@swc/core": true
  "aws-sdk": true
  "msgpackr-extract": true
  "prisma": true
  "sharp": true
  "unrs-resolver": true
