import { BadRequestException, Injectable } from "@nestjs/common";
import { Season } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import BucketType from "../s3/enums/BucketType";
import { S3Service } from "../s3/s3.service";
import { CreateSeasonDto } from "./dto/request/create-season.dto";
import { UpdateSeasonDto } from "./dto/request/update-season.dto";

@Injectable()
export class SeasonService {
  private getPosterKey(id: string) {
    return `posters/seasons/${id}`;
  }

  private async getManagedPosterUrl(id: string) {
    return this.s3Service.getReadPresignedUrl(this.getPosterKey(id), BucketType.PROCESSED);
  }

  private async assertManagedPosterUrl(id: string, posterUrl: string) {
    const backendPoster = await this.getManagedPosterUrl(id);
    if (posterUrl !== backendPoster) {
      throw new BadRequestException("Poster URL must be generated by the backend");
    }
  }

  constructor(
    private readonly prisma: PrismaService,
    private readonly s3Service: S3Service,
  ) {}

  async create(data: CreateSeasonDto): Promise<Season> {
    return this.prisma.season.create({ data });
  }

  async findAll(titleId?: string): Promise<Season[]> {
    const where = titleId ? { titleId } : {};
    return this.prisma.season.findMany({
      where,
      orderBy: { number: "asc" },
    });
  }

  async findOne(id: string): Promise<Season | null> {
    return this.prisma.season.findUnique({ where: { id } });
  }

  async update(id: string, data: UpdateSeasonDto): Promise<Season> {
    const season = await this.findOne(id);
    if (!season) {
      throw new BadRequestException(`Season with id ${id} not found`);
    }

    if (data.posterUrl !== undefined) {
      this.assertManagedPosterUrl(id, data.posterUrl);
    }

    return this.prisma.season.update({ where: { id }, data });
  }

  async createPosterUploadingUrl(id: string): Promise<{ uploadUrl: string; posterUrl: string }> {
    const season = await this.findOne(id);
    if (!season) {
      throw new BadRequestException(`Season with id ${id} not found`);
    }

    const key = this.getPosterKey(id);
    const uploadUrl = await this.s3Service.getUploadPresignedUrl(key, BucketType.PROCESSED, 120);
    const posterUrl = await this.s3Service.getReadPresignedUrl(key, BucketType.PROCESSED);

    return { uploadUrl, posterUrl };
  }

  async delete(id: string): Promise<Season> {
    const season = await this.prisma.season.findUnique({
      where: { id },
      include: { episodes: true },
    });

    if (!season) {
      throw new BadRequestException(`Season with id ${id} not found`);
    }

    for (const episode of season.episodes) {
      await this.s3Service.deleteObject(episode.id, BucketType.RAW);
    }

    await this.s3Service.deleteObject(this.getPosterKey(id), BucketType.PROCESSED);
    await this.s3Service.deleteFolder(`videos/${season.titleId}/${id}/`, BucketType.PROCESSED);

    return this.prisma.season.delete({ where: { id } });
  }
}
