services:
  client:
    container_name: "client"
    build:
      context: ../../
      dockerfile: client/Dockerfile
      target: runner
      args:
        BACKEND_API_URL: "http://api:3000"
        NEXT_PUBLIC_BACKEND_API_URL: "http://localhost:3000"
        NEXT_PUBLIC_APP_URL: "http://localhost:4000"
        NEXT_PUBLIC_REMOTE_IMAGE_HOSTNAME: "m.media-amazon.com"
    command: sh -c "yarn workspace client dev"
    environment:
      NODE_ENV: "development"
      BACKEND_API_URL: "http://api:3000"
      NEXT_PUBLIC_BACKEND_API_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_URL: "http://localhost:4000"
      NEXT_PUBLIC_REMOTE_IMAGE_HOSTNAME: "m.media-amazon.com"
      NEXT_PUBLIC_S3_IMAGE_PORT: "4000"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../client:/app/client
      - ../../package.json:/app/package.json
      - ../../yarn.lock:/app/yarn.lock
      - ./volumes/client/node_modules:/app/node_modules
      - ./volumes/client/package_node_modules:/app/client/node_modules
      - ./volumes/client/.next:/app/client/.next
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://client:4000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      api:
        condition: service_healthy

  api:
    container_name: "api"
    build:
      context: ../../
      dockerfile: api/Dockerfile
      target: runner
    command: sh -c "yarn workspace api db:prepare && yarn workspace api dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://root:root@db:5432/watchly?schema=public"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      S3_ACCESS_KEY_ID: "localstack"
      S3_SECRET_ACCESS_KEY: "localstack"
      S3_REGION: "us-east-1"
      S3_RAW_BUCKET_NAME: "raw"
      S3_PROCESSED_BUCKET_NAME: "content"
      S3_ENDPOINT_INTERNAL: "http://localstack:4566"
      S3_ENDPOINT_PUBLIC: "http://localhost:4000"
    volumes:
      - ../../api:/app/api
      - ../../package.json:/app/package.json
      - ../../yarn.lock:/app/yarn.lock
      - ./volumes/api/node_modules:/app/node_modules
      - ./volumes/api/package_node_modules:/app/api/node_modules
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q -O /dev/null http://api:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - db
      - redis
      - localstack

  db:
    image: "postgres:16"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "watchly"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: "redis:8.4.0"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  localstack:
    image: "gresau/localstack-persist:4"
    container_name: "localstack"
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - PERSISTENCE=1
      - PARITY_AWS_ACCESS_KEY_ID=localstack
      - PARITY_AWS_SECRET_ACCESS_KEY=localstack
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_ALLOWED_METHODS=*
      - EXTRA_CORS_EXPOSE_HEADERS=*
      - DEBUG=1
    volumes:
      - "localstack_data:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx:
    image: "nginx:latest"
    container_name: "nginx"
    # network_mode: "host"
    volumes:
      # config files
      - ./volumes/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/config/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - "4000:4000"
    depends_on:
      client:
        condition: service_healthy

volumes:
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local
  backend_node_modules:
    driver: local
  postgres_data:
  redis_data:
  localstack_data:
