import { BadRequestException } from "@nestjs/common";
import BucketType from "./enums/bucket-type.enum";
import { S3Service } from "./s3.service";

export async function assertManagedPosterUrl(
  s3Service: S3Service,
  posterKey: string,
  posterUrl: string,
): Promise<void> {
  const managedUrl = await s3Service.getReadPresignedUrl(posterKey, BucketType.PROCESSED);

  let submittedPath: string;
  let managedPath: string;
  try {
    submittedPath = new URL(posterUrl).pathname;
    managedPath = new URL(managedUrl).pathname;
  } catch {
    throw new BadRequestException("Poster URL must be generated by the backend");
  }

  if (submittedPath !== managedPath) {
    throw new BadRequestException("Poster URL must be generated by the backend");
  }
}
