import { BadRequestException } from "@nestjs/common";
import BucketType from "./enums/bucket-type.enum";
import { S3Service } from "./s3.service";

export async function assertManagedPosterUrl(
  s3Service: S3Service,
  posterKey: string,
  posterUrl: string,
  defaultPosterUrl?: string,
): Promise<void> {
  if (defaultPosterUrl !== undefined && posterUrl === defaultPosterUrl) return;

  const managedUrl = await s3Service.getReadPresignedUrl(posterKey, BucketType.PROCESSED);
  if (posterUrl !== managedUrl) {
    throw new BadRequestException("Poster URL must be generated by the backend");
  }
}
