name: Build Client

on:
  pull_request:
    paths:
      - "apps/client/**"
      - "package.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main
      - develop
    paths:
      - "apps/client/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Client
        run: pnpm --filter client build
